version: '3'
services:
  php-cli:
    image: php:7.4-cli
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
  composer:
    image: composer:2
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached